import type { Beat, Collection, Tag } from "./types"

// Generate random waveform data
const generateWaveform = (length = 100) => {
  return Array.from({ length }, () => Math.random() * 0.8 + 0.2)
}

export const dummyTags: Tag[] = [
  { id: "tag1", name: "Trap", color: "#FF5733" },
  { id: "tag2", name: "Lo-Fi", color: "#33FF57" },
  { id: "tag3", name: "Drill", color: "#3357FF" },
  { id: "tag4", name: "Boom Bap", color: "#F033FF" },
  { id: "tag5", name: "Melodic", color: "#FF3393" },
  { id: "tag6", name: "Dark", color: "#33FFF5" },
]

export const dummyBeats: Beat[] = [
  {
    id: "beat1",
    title: "Midnight Vibes",
    artist: "Producer X",
    bpm: 140,
    key: "C Minor",
    duration: 185,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio1.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag1", "tag5"],
    createdAt: "2023-09-15T12:00:00Z",
    plays: 1245,
  },
  {
    id: "beat2",
    title: "Summer Haze",
    artist: "Beat Maker Y",
    bpm: 95,
    key: "G Major",
    duration: 210,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio2.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag2"],
    createdAt: "2023-09-10T14:30:00Z",
    plays: 876,
  },
  {
    id: "beat3",
    title: "Urban Flow",
    artist: "DJ Z",
    bpm: 128,
    key: "D Minor",
    duration: 195,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio3.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag1", "tag3"],
    createdAt: "2023-09-05T09:15:00Z",
    plays: 2341,
  },
  {
    id: "beat4",
    title: "Chill Waves",
    artist: "Producer X",
    bpm: 85,
    key: "A Minor",
    duration: 230,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio4.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag2", "tag5"],
    createdAt: "2023-08-28T16:45:00Z",
    plays: 1532,
  },
  {
    id: "beat5",
    title: "Street Anthem",
    artist: "Beat Maker Y",
    bpm: 145,
    key: "F Minor",
    duration: 175,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio5.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag3", "tag6"],
    createdAt: "2023-08-20T11:30:00Z",
    plays: 987,
  },
  {
    id: "beat6",
    title: "Neon Lights",
    artist: "DJ Z",
    bpm: 110,
    key: "E Minor",
    duration: 205,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio6.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag1", "tag5", "tag6"],
    createdAt: "2023-08-15T13:20:00Z",
    plays: 1876,
  },
  {
    id: "beat7",
    title: "Golden Era",
    artist: "Producer X",
    bpm: 90,
    key: "B Minor",
    duration: 215,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio7.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag4"],
    createdAt: "2023-08-10T10:00:00Z",
    plays: 2145,
  },
  {
    id: "beat8",
    title: "Future Bounce",
    artist: "Beat Maker Y",
    bpm: 130,
    key: "G Minor",
    duration: 190,
    waveformData: generateWaveform(),
    audioUrl: "https://example.com/audio8.mp3",
    imageUrl: "/placeholder.svg?height=300&width=300",
    tagIds: ["tag1", "tag3", "tag5"],
    createdAt: "2023-08-05T15:10:00Z",
    plays: 1432,
  },
]

export const dummyCollections: Collection[] = [
  {
    id: "collection1",
    name: "Favorites",
    description: "My favorite beats",
    beatIds: ["beat1", "beat4", "beat6"],
    createdAt: "2023-09-01T10:00:00Z",
  },
  {
    id: "collection2",
    name: "For Recording",
    description: "Beats for upcoming recording session",
    beatIds: ["beat2", "beat7"],
    createdAt: "2023-08-15T14:30:00Z",
  },
  {
    id: "collection3",
    name: "Inspiration",
    description: "Beats that inspire me",
    beatIds: ["beat3", "beat5", "beat8"],
    createdAt: "2023-07-20T09:45:00Z",
  },
]

